### ISSUE TITLE
SET_TYPEOF

### ISSUE THREAD

**Issue by edzer** [rho-devel/rho#48]
Several R packages (such as `xts`) use `SET_TYPEOF` in C code, as it is advertised in _Writing R Extensions_. Rho fails to install such packages. Could Rho provide a dummy `SET_TYPEOF`, or would that create more trouble?

**Comment by kmillar** [comment]
Unfortunately it's more complicated than that.  `SET_TYPEOF` is being used to convert PairLists into Expressions.  Inserting a dummy implementation that didn't do that conversion wouldn't work, as Rf_eval() on an Expression does a function call and on a PairList it just returns the argument.

In rho these two objects don't have the same representation, or even the same size, so doing the conversion isn't going to be straight-forward.

I'm about to do a bunch of work on compatibility, and I'll get this solved as part of that.

**Comment by kmillar** [comment]
It looks like there's only 23 CRAN packages that call `SET_TYPEOF` most look to be trivial to change so that they don't need it.  That may be the easier fix.

**Comment by kmillar** [comment]
Fixed in #83.
