### ISSUE TITLE
Roxygen2

### ISSUE THREAD

**Issue by Ironholds** [rho-devel/rho#8]
Would using Roxygen2 to generate the markdown constitute too much of a circular process to be acceptable? ;p

**Comment by kmillar** [comment]
I'm not quite sure what you're proposing here.

Are you thinking of taking the existing .Rd files, incorporating their comments as roxygen documentation inside the .R files and the having the .Rd files get auto-regenerated with Roxygen2?

The circularity here doesn't bother me, but I'd be surprised if R-core was interested in making that type of change, and again, IMO keeping the codebases in sync as much as possible is more important than the advantages that Roxygen2 provides.

**Comment by Ironholds** [comment]
Yeah, I doubt they would be. I guess a better base question here would be; what's the goal here? Developing a C++ version, or developing a C++ alternative?

**Comment by kmillar** [comment]
As always, there are multiple goals.  This is my ranking, in order of decreasing importance.  Others may have different priorities.

  - Fully compatible R implementation, both now and into the future.
  - Good performance
  - Good code quality / maintainability
  - An open team where anyone with interest is welcome and can contribute
  - Acceptance within the wider R community
  - Support R-core's development when it aligns with work that we're doing

IMO, C++ is not a goal, except to the extent that using it supports the other goals.

Given this list, making significant changes to and/or rewriting existing C code benefits the second and third priorities, but makes the first one harder, so there's a trade-off to be made there.  On the other hand, sending improvements upstream may be harder, but supports all of these goals.

As always, there's no perfect answer.
